org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2
fabric_api_version=0.161.0+26.3

mod_version=1.0.0
maven_group=de.samu.pvpbot
archives_base_name=pvpbot

anthropic_version=2.66.0
voicechat_api_version=2.6.24
voicechat_version=fabric-2.6.24+26.3
